services:
#    basket_api.example:
#        class: Binary\Bundle\FruitBasketApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    form.basket:
        class: Binary\Bundle\FruitBasketApiBundle\Form\BasketType
        tags:
            - { name: form.type }
